# Build a general Node.js project with npm.

trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    cd src
    npm install
    npm install '@espruino-tools/core'
    npm run build
    npm run deploy
  displayName: 'Build and Deploy'

- task: PublishPipelineArtifact@1
  inputs:
    artifactName: 'gh-pages'
    targetPath: '$(Build.SourcesDirectory)/dist'
  condition: succeededOrFailed()

- task: GitHubPages@3
  inputs:
    githubConnection: 'LewisTrundle'
    repositoryName: 'L4-Individual-Project'
    folderPath: 'dist'
    targetBranch: 'gh-pages'
    useExternalRepository: true