# Build a general Node.js project with npm.

trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    cd src
    npm install
    npm install 'espruino-tools/core'
    npm run build
  displayName: 'npm install and build'